{% set name = "anaconda-verify" %}
{% set version = "1.3.8" %}
{% set checksum = "5f5835801c6c205bb87a772353388a7073bb9891d869e147594736a9e339d770" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ContinuumIO/anaconda-verify/archive/{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - anaconda-verify = anaconda_verify.main:main

requirements:
  host:
    - pip
    - python

  run:
    - python
    - pyyaml

test:
  imports:
    - anaconda_verify

  commands:
    - anaconda-verify --help

about:
  home: https://github.com/ContinuumIO/anaconda-verify
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: tool for validating conda recipes and conda packages

extra:
  recipe-maintainers:
    - jakirkham
