{% set name = "anaconda-verify" %}
{% set version = "1.3.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/ContinuumIO/anaconda-verify/archive/{{ version }}.tar.gz
  sha256: 5f5835801c6c205bb87a772353388a7073bb9891d869e147594736a9e339d770

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - anaconda-verify = anaconda_verify.main:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pyyaml

test:
  requires:
    - python {{ python_min }}
  imports:
    - anaconda_verify

  commands:
    - anaconda-verify --help

about:
  home: https://github.com/ContinuumIO/anaconda-verify
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: tool for validating conda recipes and conda packages

extra:
  recipe-maintainers:
    - jakirkham
