# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "hT+iflL6hxIuwR4Cb2+O3wDAi8BsHBVol2D1Z7MsECfmlBJjE4DIJyJLzwcc521eqZDKqih4jyEnvCXGLPWxXbOvs23LkBWY4TQNWsY6qTX1r9SceooLb+x/ta0HQYN4ZKAFE+PzLVUMQG9bLFIldJd5hJzxE6OEcnC8sy6LG5vjQd9J5rew6SJReUP7vJmIhJVJCTa3qv8Xd3FMWJPV0bVmzdqtLGLCd6cRuuREj00HIveJxlKJCAPkauV/eqkAid8ucvoA3iJqxEMnPqbNmzc6AY7fS7n501Ehj5bhs4sR7HLKVMHa6xo+wIygQcGWuRVokoX1h/8QdmlxtNJFWITqGdpIsTx4TRkONEpTllD5PWRcKpB3t4mnolqofQDmjpyhzxiaOpDpJ9ZCirFWHjpCCWPm/t31PLsG4Nk9D1bVWkd++JUEiatEEUpv99sXpWjYkdEI+2tDLsfDMc1lu8b3JI1pFA9YsASwQLLP/j2KhGNfZzE8O9KPkfijFMVQs/oVElcFwWqX8xQUloSGbGBf8k2R8o/y8CBiMeeM/mP5j7MV+tm5nFastbInivNPT3DOzOx1c/emocfKmgGiO27VAzvqhMm3p/pD1XD9I9fJfu9dTTIFZjb479odIxQPbQhN3y4yBbKjato8vd7J2dkfMCiDI+miZGRzC0lgXu8="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
