travis:
  secure:
    BINSTAR_TOKEN: RQe2aCOUMRKMgeLi0FSVOnvuK6MCd2BREG/TPX0UKeCJrKL8O1vV3K1wdt2yNv1NNLXJ9C6xAbXgFDeeBvdcI6xPkGtGAs2RSgOuKDom/heGmGP51mi/RXa2AJ8nF59vy0h8uIGwPc9tWvQissqh0y0OITo+rs7hjpDms5/hglWDyoOVmCFKMxfzkjA5tPws9C7nZzDnzft5QEv2yefhkzbIdwNA2ohdAuNAueQAkWeG5XUnFCQFXUKSx8ORVbv+0qdoX56ZmJF8gdvUHVDDRzwRkhzEDXU10XaPehkjs93sDygCXwV5Rt/ByN12fhjVUL6QYswcRXSFadIFUPUxvT0N3iukkWK1Hfv/HsnaiIHGmbEvX6RNI02iIbkhUHxGfldwKYpPJ7U5s+hqFG6f6f5JYTl4UGurXOi4TRrU/NNJzusEOHtUg8ATttzF190vqNhf5xN4X6UIn1ku0hXD+ZTlbuTQBvjin2/wqaGOdVQPiDY72y0cc0KuWAbcrFz4uJ9xY04fznb23NCCCeKPU56aMI1PpM08LvhHPSNmzgYCpUYmOxG+tTF8bR0+zv6zlVeT0luufxZYVzEo8YQqGwZH3nCrIXGCK4vR1BAztVpsxMp5/hDEYuHFInWY3sDy3D6ntji9P7Tza6TLjDxRU/Qyy5u2yS4WXt3EXr4Ovpk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
