travis:
  secure:
    BINSTAR_TOKEN: X0HucYj5GjlgQnwObFT+SYyw1V1TezbnsIPv0vjkxHJGTpbPe8dfu3hROMc9qNsqtdk5CA/ZzFVWY28x7KBhMpy1G05381uNz8NSVyU5S8NW0XCspBd7OiVUU+lbUS/ME+uNpPmI+crZ0CqpiXGZsYhJCEbP2DRo+G+8kNOHE90EA70jQK3SghpWYBBGUVq5EtNhCOdgDlVrXGYjGLXlIAHxKxElCYRvaBT1hdORV9MVMYWhBYTwu2zlOiw05yAZ5Zf1i+W8eVfDGLaVJviQ+sNxibw9+yiMGkHiKLciYDtpWSGrNYOffubktn266INFNkxbQ/CZRo18eChg+SJwMx6Y3hm9YWaR6ZHcBjzr8m5D/BnGNB91IBNIXm2173Jw3Q02DGthzDy1JEWjEBR41UBtNoICySADxN3G6AEKFCMhDdi9sisI31QHaEnCTzCPUhHofucZGHOtfepi0cpUUT1HE/T5gOZqmsG5IkBc8tlM0DlhLjObWjpOlhZT/f7DisHq9XO3/+nvSB36QjBROd7eo/sPOE9tDl5ZfGOTZA1HIxCNVAi74UTmMH+Kxx9BVGmLcudIZuEMktyPWfm7pMRPGpBVVYHjATV8rzVIboM4LqXBDHpqeZrSYqHxxZo52NXNxKcOyXAimeAZn/mp6p068qekr7a4bTXAGRfBnfo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
